my_app/browser/routes.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May 13 14:49:41 2020

@author: muellerM@ieg-mainz.de
"""

from flask import Blueprint, session, render_template, url_for, flash, redirect, request, jsonify, json, current_app
from flask_login import login_required, current_user
from pathlib import Path
from .. import db
from ..exporter.routes import getExportedFiles, getDownloadableFiles
from ..io.web import Transkribus_Web
from ..models import Comment
import sys
import re


cts_bp = Blueprint('cts', __name__)

@cts_bp.route("/cts", methods = ['GET'])
@login_required
def cts():
    return "Please specify a protocol: /cts/<protocol> (tr = Transkribus)."

@cts_bp.route("/cts/tr")
def tr():
    TR = Transkribus_Web(session_id=session['JSESSIONID'])
    TR.list_collections()
    current_user.colcache = str(json.dumps(TR.cols))
    db.session.commit()
    return {'tr': {'cols': TR.cols}}, 200

@cts_bp.route("/cts/tr/<string:colId>")
def col(colId):
    TR = Transkribus_Web(session_id=session['JSESSIONID'])
    TR.cols = json.loads(current_user.colcache)
    if TR.list_documents_in_collection(colId):
        current_user.colcache = str(json.dumps(TR.cols))
        db.session.commit()
        return TR.cols[colId], 200
    else:
        return f"Collection {colId} not found.", 404

@cts_bp.route("/cts/tr/<string:colId>/<string:docId>")
def doc(colId, docId):
    TR = Transkribus_Web(session_id=session['JSESSIONID'])
    TR.cols = json.loads(current_user.colcache)
    if TR.list_pages_in_document(colId, docId):
        current_user.colcache = str(json.dumps(TR.cols))
        db.session.commit()
        
        getComments(TR, colId, docId)
        
        return TR.cols[colId]['docs'][docId], 200
    else:
        return f"Document {docId} not found in collection {colId}", 404

@cts_bp.route("/cts/tr/<string:colId>/<string:docId>/<string:pageNr>/edit")
def edit(colId, docId, pageNr):
    """ Redirect to the 'editor' module to open pageNr. """

    # First, check if colId, docId and pageNr are already cached.
    # Load them, if necessary.
    TR = Transkribus_Web(session_id=session['JSESSIONID'])
    TR.cols = json.loads(current_user.colcache)
    if docId not in TR.cols[colId]['docs']:
        TR.list_documents_in_collection(colId)
        current_user.colcache = str(json.dumps(TR.cols))
        db.session.commit()
    if pageNr not in TR.cols[colId]['docs'][docId]['pages']:
        TR.list_pages_in_document(colId, docId)
        current_user.colcache = str(json.dumps(TR.cols))
        db.session.commit()
    
    return redirect(url_for('editor.editor', action="open", colId=colId, docId=docId, pageNr=pageNr))

@cts_bp.route("/cts/resolver", methods=['GET'])
def resolve():
    """ Resolve strings containing a cts URN and (optionally).
        TODO: Let the user define an action that should be executed with the requested text. """
    cts = request.args.get('urn') # required
    #action = request.args.get('action') # optional
    
    cts = re.sub("@.*", "", cts)                     # cut off subreference (wordIdx)
    cts = re.sub("(.*:.*:.*)[\.|:].*", "\g<1>", cts) # cut off region and line reference (old regex: (.*:.*:.*)\..* )
    cts = re.sub("[\.:]", "/", cts)                  # convert to URL path
    
    print("CTS-RESOLVER: Opening", f"/cts/{cts}/edit")
    
    return redirect(cts+"/edit")

    

browser_bp = Blueprint('browser', __name__)

@browser_bp.route("/browser", methods = ['GET'])
@login_required
def browser():
    """ This is the landing page after login. At first visit, it 
        downloads the list of collections from Transkribus. If the 
        user opens a collection or document, the browser will fetch 
        more data using the /cts/tr endpoint. """
    
    TR = Transkribus_Web(session_id=session['JSESSIONID'])
    TR.list_collections()
    current_user.colcache = str(json.dumps(TR.cols))
    db.session.commit()
    
    current_app.logger.info("collections loaded, building list of exported files")
    # Build a dictionary of the available json files in the cache on disk (i.e. pages that have been "dumped" already):
    exportedFiles = getExportedFiles()
    
    current_app.logger.info("building list of downloadable files")
    # Build a list of already exported xml files in the cache on disk:
    downloadableFiles = getDownloadableFiles()

    current_app.logger.info("ready. rendering template")

    return render_template('browser.html', 
                           cols=TR.cols, 
                           exportedFiles=exportedFiles, 
                           downloadableFiles=downloadableFiles, 
                           comparableFiles=[],
                           formats=["TEI for LERA", "TSV for TRACER","CSV for comparison"],
                           pythonversion=sys.version.replace("\n", " "),
                           )


def getComments(TR, colId, docId):
    comments = Comment.query.all()
    for comment in comments:
        cts = explode_cts(comment.cts)
        #print("DEBUG Comments on page", cts['colId'], f"({type(cts['colId'])})", 
        #      cts['docId'], f"({type(cts['docId'])})", 
        #      cts['pageNr'], f"({type(cts['pageNr'])})")
        if cts['colId'] == colId and cts['docId'] == docId:
            TR.cols[cts['colId']]['docs'][cts['docId']]['pages'][cts['pageNr']]['comment'] = 'true'

    return TR

def explode_cts(cts):
    """ Split a cts URI into its parts and return them as a dict. """
    #f"tr:{colId}.{docId}:{pageNr}:{region and line}@wordIdx"
    elements = cts.split(":")    
    protocol = elements[0]
    document = elements[1]
    
    if len(elements) == 4:
        pageNr = elements[2]
        regionLine = elements[3]
    elif len(elements) == 3:
        pageNr, regionLine = elements[2].split(".")
        
    if "@" in regionLine:
        regionLine, wordIdx = regionLine.split("@")
    else:
        wordIdx = ""
    colId, docId = document.split(".")
    return {'protocol': protocol,
            'colId': colId,
            'docId': docId,
            'pageNr': pageNr,
            'regionLine': regionLine,
            'wordIdx': wordIdx}

my_app/dictionary/routes.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Endpoints for the communication of the server with the client's dictionary.html/dictionary.js.
Provides database operations to manage the user dictionary and the list of printer's errors.

Created on Wed May 20 17:19:00 2020

@author: muellerM@ieg-mainz.de
"""

from flask import Blueprint, render_template, url_for, flash, redirect, request, jsonify, json, session, current_app
from flask_login import login_required, current_user
from .. import db
from ..models import User, Dictionary, PrintersError
import csv
import requests

# Functions for loading data from the database and Google Spreadsheets:
#######################################################################
def load_printers_errors():
    """ Load the printer's errors from the database. """
    try:
        all_printerserrors = PrintersError.query.all()
        printerserrors = {}
        for error in all_printerserrors:
            printerserrors[error.pattern] = {'correction': error.replacement}
        return printerserrors
    except:
        return False

def load_user_dictionary():
    """ Update SymSpell with the entries from the user dictionary. """
    user_dictionary = Dictionary.query.all()
    additions = 0
    deletions = 0
    errors = 0
    for entry in user_dictionary:
        if entry.action == "add":
            # Add to SymSpell:
            if current_app.dictionary.sym_spell.create_dictionary_entry(entry.word, entry.count):
                #print(f'USER-DICTIONARY: added "{entry.word}" as a new word to SymSpell.')
                pass
            else:
                #print(f'USER-DICTIONARY: added (below threshold) or updated "{entry.word}" in SymSpell.')
                pass
            additions += 1
        elif entry.action == "del":
            # Delete from SymSpell:
            if current_app.dictionary.sym_spell.delete_dictionary_entry(entry.word):
                #print(f'USER-DICTIONARY: "{entry.action}" "{entry.word}" from SymSpell.')
                deletions += 1
            else:
                current_app.logger.info(f'USER-DICTIONARY: ERROR: could not delete "{entry.word}": not found.')
                errors += 1
    current_app.logger.info(f'USER-DICTIONARY: Added/updated {additions}, deleted {deletions} words to/from SymSpell.')
    if errors > 0:
        current_app.logger.info(f'USER-DICTIONARY: There were {errors} errors.')

    return True

def import_from_google(source):
    """ To import data from Google Sheets, provide a source:
            'Dictionary' or 'PrintersErrors'
        
        The URLs for Google Sheets are stored in config.py:
            url = current_app.config['DICTIONARY']
        and
            url = urrent_app.config['PRINTERS_ERRORS'] """

    if source == 'Dictionary':
        url = current_app.config['DICTIONARY']
    elif source == 'PrintersErrors':
        url = current_app.config['PRINTERS_ERRORS']

    current_app.logger.debug(f"DICTIONARY: url\n{url}")

    try: 
        r = requests.get(url)
        
        lines = r.content.decode().splitlines()
        
        current_app.logger.debug(f"DICTIONARY: csv\n{lines}")
        csv_reader = csv.reader(lines)
        
        additions = 0
        skipped = 0
        
        for idx, row in enumerate(csv_reader):
            if idx == 0:
                fieldnames = row # Split only the first line#
            else:
                if not row[0].startswith("#"):   # skips comments
                    key = row[0]
                    value = row[1]
    
                    # Treat every target table differently:        
                        
                    # Add to user dictionary in our database:
                    if source == "Dictionary":
                        if Dictionary.query.filter_by(word=key).first():
                            skipped += 1
                            current_app.logger.info(f"DICTIONARY: Skipping '{key}': already in dictionary")
                        else:
                            new_word = Dictionary(word=key, 
                                                  count=10, 
                                                  action="add",
                                                  userid=current_user.id,
                                                  cts="tr:GoogleSheets:Dictionary")
                            db.session.add(new_word)
                            db.session.commit()
            
                            # Add to symspell:
                            current_app.dictionary.sym_spell.create_dictionary_entry(new_word.word, new_word.count)
                            
                            additions += 1
                            current_app.logger.info(f"DICTIONARY: added {key}")
    
                    elif source == "PrintersErrors":
                        if PrintersError.query.filter_by(pattern=key).first():
                            skipped += 1
                            current_app.logger.info(f"PRINTERS_ERROR: Skipping '{key}': already in the list of printer's errors")
                        else:
                            new_pattern = PrintersError(pattern=key, 
                                                        replacement=value, 
                                                        userid=current_user.id,
                                                        cts="tr:GoogleSheets:PrintersErrors")
                            db.session.add(new_pattern)
                            db.session.commit()
                            
                            additions += 1
                            current_app.logger.info(f"PRINTERS_ERROR: added {key} → {value}")
                
            if source == "PrintersErrors":
                cleaner = current_app.cleaner
                cleaner.printers_errors = load_printers_errors()

    except: 
        current_app.logger.error(f"DICTIONARY: Could not load Google Sheet from {url}.")

    message = f"IMPORT: Finished import from Google Sheets to {source}:\n{additions} additions, {skipped} skipped."
    current_app.logger.info(message)
    return message


    
# The actual dictionary functionality:   
######################################

dictionary_bp = Blueprint('dictionary', __name__)

@dictionary_bp.route("/dictionary", methods=['GET', 'POST'])
@login_required
def dictionary():
    action = request.args.get('action') # required
    word = request.args.get('word') # optional
    cts = request.args.get('cts')   # optional

    if request.method == "GET":
        
        # Return an EDITABLE VIEW of the user dictionary
        if action == 'edit':
            all_words = Dictionary.query.all()
            words = []
            for word in all_words:
                words.append({'id': word.id,
                              'word': word.word,
                              'count': word.count,
                              'timestamp': word.timestamp.astimezone().isoformat(timespec='seconds'), #strftime("%Y-%m-%d, %H:%M:%S", gmtime()),
                              'user': User.query.filter_by(id=word.userid).first().username,
                              'cts': word.cts,
                              'action': word.action,                    
                              'comment': word.comment})

            all_printerserrors = PrintersError.query.all()
            printerserrors = []
            for error in all_printerserrors:
                printerserrors.append({'id': error.id,
                                       'pattern': error.pattern,
                                       'replacement': error.replacement,
                                       'timestamp': error.timestamp.astimezone().isoformat(timespec='seconds'), #strftime("%Y-%m-%d, %H:%M:%S", gmtime()),
                                       'user': User.query.filter_by(id=error.userid).first().username,
                                       'cts': error.cts,                
                                       'comment': error.comment})


            return render_template('dictionary.html', data=json.dumps({'words': words,
                                                                       'printerserrors': printerserrors}))

        
        # CHECK a word in the dictionary
        elif action == 'check':
            cleaner = current_app.cleaner
            W, wc = cleaner.dictionary.check_word(word)
            symspell = Dictionary.query.filter_by(word=word).first()
            current_app.logger.debug(f"DICTIONARY: Checked for {word}: {W}, {wc}.")
            if word == "":
                return jsonify(success = 'neutral',
                               response = '')                
            elif symspell:
                if symspell.action != "del":
                    return jsonify(success = 'success',
                                   response = '(user dictionary)')
                else:
                    return jsonify(success = 'error',
                                   response = 'not found (deleted by user)')
            elif W:
                return jsonify(success = 'success',
                               response = f'(word count = {wc})')
            elif cleaner.whitaker.check(word):
                return jsonify(success = 'success',
                               response = "(Whitaker's Words)")               
            else:
                return jsonify(success = 'error',
                               response = 'not found')

            
            #return render_template('dictionary.html', word=word, colId=colId, docId=docId, pageNr=pageNr)
        
        # RELOAD replacement TABLES
        elif action == 'reloadtables':
            cleaner = current_app.cleaner
            if cleaner.reload_tables():
                return jsonify(success = 'success',
                               response = 'Reloaded successufully from Google Docs.')
            else:

my_app/templates/base.html
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> 
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@5.8.55/css/materialdesignicons.css">
    <!--The following line imports the vue.js framework in development mode, i.e. the framework shows error messages for debugging. -->
    <script src="https://unpkg.com/vue@2.6.11"></script>
    <!--For production deployment, turn on production mode by linking the "min" version of vue.js instead of the 'normal' version:-->
    <!--<script src="https://unpgk.com/browse/vue@2.6.11/dist/vue.min.js"></script>-->

    <link rel="stylesheet" href="{{ url_for('static', filename='base.css') }}">
    {% block header %}
    {% endblock %}
    <title>{% block windowtitle %}{% endblock %}</title>
</head>
<body>
<div id="vue-app">
    <header class="w3-container w3-theme w3-card">
        <h3>{% block title %}{% endblock %}
            <nav class="w3-right w3-large w3-theme">
                {% if current_user.is_authenticated %}
                <div class="w3-dropdown-hover w3-theme">
                    <button class="w3-button w3-theme" title="bookmarks">
                        <i class="mdi mdi-book-multiple"></i>
                    </button>
                    <div class="w3-dropdown-content w3-bar-block w3-border">
                        <a href="https://docs.google.com/document/d/15CI-Y5h1yv_yyNGPsrstaE1XEXSSCj34tk8ixYrJXbc/edit#" 
                            title="Transkribus notes on Google Drive"
                            class="w3-bar-item w3-button"
                            target="notes">
                            <i class="mdi mdi-google-drive"></i> Notes</a>
                        <a href="https://docs.google.com/spreadsheets/d/1clOw7TzM2kvwTWIOkrtcB9I_aTK_7DBwCDQR3fbteA8/edit#gid=701239194" 
                            title="Transkribus todo on Google Drive"
                            class="w3-bar-item w3-button"
                            target="todo">
                            <i class="mdi mdi-google-drive"></i> Todo</a>
                        <a href="https://docs.google.com/spreadsheets/d/1BALDiEL3h71xUgQuXx9aChAhI_KbFX3un1Q_4Onob28/edit#gid=0" 
                            title="Transkribus tables on Google Drive"
                            class="w3-bar-item w3-button"
                            target="tables">
                            <i class="mdi mdi-google-drive"></i> Tables</a>
                        <a href="https://www.lexilogos.com/keyboard/greek_ancient.htm"
                            title="Virtual keyboard for ancient Greek"
                            class="w3-bar-item w3-button"
                            target="greekkbd">Greek keyboard</a>                        
                    </div>
                </div>
                <button class="w3-button w3-theme" title="help"
                    @click="modals.help = true">
                    <i class="mdi mdi-help-circle"></i>
                </button>
                <button class="w3-button w3-theme" title="logout"
                    onclick="window.location.href = '{{ url_for('auth.logout') }}';"><i class="mdi mdi-logout"></i></a>
                </button>
                {% else %}
                <button class="w3-button w3-theme" title="register"
                    onclick="window.location.href = '{{ url_for('auth.register') }}';">Register</i></a>
                </button>
                <button class="w3-button w3-theme" title="login"
                    onclick="window.location.href = '{{ url_for('auth.login') }}';">Login</a>
                </button>
                {% endif %}
            </nav>
        </h3>
    </header>
    
    <main class="w3-container w3-section">
        {% for category, message in get_flashed_messages(with_categories=true) %}
            {% if message != None %}
                <div class="w3-panel w3-display-container flash-{{ category }}">
                    <span onclick="this.parentElement.style.display='none'"
                          class="w3-button w3-display-topright">&times;</span> 
                    <p>{{ message | safe }}</p>
                </div>
            {% endif %}
        {% endfor %}
        {% block content %}{% endblock %}
    </main>
    <footer class="w3-container w3-text-theme w3-theme-light">
        {% block footer %}{% endblock %}
        <p><small>¯\_(ツ)_/¯ Made for extreme Digital <abbr title="Gedöns [​gə'dø​ːns], n (uncountable) – German for 'stuff, things, junk, fuss'.">Gedöns</abbr> Management, Main💤 2020–2021.</small></p>
    </footer>
</div>
{% block script %}{% endblock %}
</body>
</html>

my_app/templates/critical_edition.html
<!DOCTYPE html>
    <html lang="de">
    <head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> 
		<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue.css">
		<link rel="stylesheet" href="https://cdn.materialdesignicons.com/5.4.55/css/materialdesignicons.min.css">
		<script src="https://unpkg.com/vue"></script>
        <style>
			p { width:300px; line-height:2em; }

			span.annotation { border-bottom:2px solid; }

			span.annotation span.annotation { padding-bottom:3px; }

			span.annotation span.annotation span.annotation { padding-bottom:6px; }

			span.annotation span.annotation span.annotation span.annotation { padding-bottom:9px; }

			span[data-uid="001"] { border-color:orange; }
			span[data-uid="002"] { border-color:blue; }
			span[data-uid="003"] { border-color:red; }
			span[data-uid="004"] { border-color:green; }
        </style>
        <title></title>
    </head>
    <body>
		<p>
			Lorem <span class="annotation" data-uid="004">ipsum dolor <span class="annotation" data-uid="001">sit amet, <span class="annotation" data-uid="002">consectetuer adipiscing</span> elit.</span> Aenean commodo ligula eget dolor. Aenean massa. <span class="annotation" data-uid="002">Cum sociis <span class="annotation" data-uid="001">natoque penatibus et <span class="annotation" data-uid="003">magnis</span> dis parturient montes, nascetur</span> ridiculus mus.</span> Donec quam felis, ultricies nec, <span class="annotation" data-uid="002">pellentesque eu, </span><span class="annotation" data-uid="001"><span class="annotation" data-uid="002">pretium</span> quis, sem.</span> Donec pede justo, fringilla vel, aliquet nec,</span> vulputate eget, arcu.
		</p>
	</body>

my_app/templates/exporter.html
{% extends 'base.html' %}

{% block title %}
    Exporter
{% endblock %}

{% block header %}
    <h1>Exporter</h1>
    <link rel="stylesheet" href="{{ url_for('static', filename='exporter.css') }}">
    <script type="text/javascript">
        var cols = {{ cols|safe }}; // transfer data from flask to vue.js
        var selected_pages = {{ selected_pages|safe }};
        var opened = {{ opened }};
        var exported_files = {{ exported_files|safe }};
        console.log(cols);
    </script>
{% endblock %}

{% block content %}
    <div id="app" class="app">
    <a href="{{ url_for('browser.browser') }}">Back to Browser</a><br/>&nbsp;<br/>
    DEBUGGING (this page is work in progress!):<br/>
    cols: [[ selected_collections ]]<br/>
    docs: [[ selected_documents ]]<br/>
    pp: [[ selected_pages ]]
        <form method="get">
            <ul class="cols">
                <li v-for="(col, colIdx) in cols">
                    [[ colIdx ]] [[ col.colName ]]
                    <ul class="docs">
                        <li v-for="(doc, docIdx) in col.docs">
                            <a @click="toggleDocs(docIdx)" :style="[opened == docIdx ? { 'font-weight': 'bold' } : {  }]">
                             [[ docIdx ]] [[ doc.docName ]] &#9660;
                            </a>
                            <ul v-show="opened == docIdx" class="pages">
                                <li><input type="checkbox"
                                           :id="colIdx+'-'+docIdx+'/all'"
                                           :name="colIdx+'-'+docIdx+'/all'"
                                           @click="select_all(colIdx, docIdx, doc.pages, $event)"
                                           :value="colIdx+'-'+docIdx"
                                           v-model="selected_documents">
                                    <label :for="colIdx+'-'+docIdx+'-all'"><em style="color: grey;">select all</em></label>
                                </li>
                                <li v-for="(page, pageIdx) in doc.pages"
                                :title="page.status">
                                    <input type="checkbox" 
                                          :id="colIdx+'-'+docIdx+'-'+pageIdx" 
                                          :name="colIdx+'-'+docIdx+'-'+pageIdx"
                                          @click="selected_documents = []" 
                                          :value="colIdx+'-'+docIdx+'-'+pageIdx"
                                          v-model="selected_pages">
                                    <label :for="colIdx+'-'+docIdx+'-'+pageIdx"><span :style="pagestyle(page.status)">&nbsp;&#128463;&nbsp;</span> page [[ pageIdx ]]</label>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
            <button type="submit" @click.prevent="exportNow">Export</button>
        </form>
        <h3>Exported files ready for download:</h3>
        <ul>
            <li v-for="f in exported_files">
                <a :href="'/exporter?action=download&file='+f">[[ f ]]</a>
                <button @click="deleteFile(f)">&#128465;</button>
            </li>
        </ul>
    </div>
    <script src="{{ url_for('static', filename='exporter.js') }}"></script>
{% endblock %}


<!-- 

-->

my_app/templates/login.html
{% extends 'base.html' %}

{% block windowtitle %}
    Login
{% endblock %}

{% block title %}
    Transkribus Spellchecker Login
{% endblock %}

{% block content %}
    <div>
        <form = method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="w3-container w3-section">
                <legend>Login</legend>
                <div>
                    {{ form.username.label }} {{ form.username(autofocus=true, class_="w3-input") }}
                </div>
                <div class="w3-margin-bottom">
                    {{ form.password.label }} {{ form.password(class_="w3-input") }}
                </div>
            </fieldset>
            <div>
                {{ form.submit(class_="w3-button w3-theme") }}
            </div>
        </form>
    </div>
{% endblock %}

my_app/templates/register.html
{% extends 'base.html' %}

{% block windowtitle %}
    Register
{% endblock %}

{% block title %}
    Transkribus Spellchecker Register
{% endblock %}

{% block content %}
    <div>
        <form = method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="w3-container w3-section">
                <legend>Register</legend>
                <div>
                    {{ form.username.label }} {{ form.username(autofocus=true, class_="w3-input") }}
                    {% if form.username.errors %}
                        {% for error in form.username.errors %}
                        {{ error }}
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="w3-margin-bottom">
                    {{ form.password.label }} {{ form.password(class_="w3-input") }}
                </div>
            </fieldset>
            <div>
                {{ form.submit(class_="w3-button w3-theme") }}
            </div>
        </form>
    </div>
{% endblock %}